# Use Python image
FROM python:3.9

# Create directory and copy writer script
RUN mkdir /app
WORKDIR /app
COPY writer.py .

# Install any dependencies (if needed)

# Run the writer script
CMD ["python", "writer.py"]
