# Use Python image
FROM python:3.9

# Create directory and copy reader script
RUN mkdir /app
WORKDIR /app
COPY reader.py .

# Install any dependencies (if needed)

# Run the reader script
CMD ["python", "reader.py"]
