version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - ipc_network
    tty: true  # Add this for better log output
    stdin_open: true  # Add this for interactive capability
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - ipc_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ipc_network:
    driver: bridge