version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu-app
    ports:
      - "8080:80"
    networks:
      - app-net

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-front
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge